=== shumailakhan4810/XML-JASON/XML/02.Schema/book.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name ="books">
    <xs:complexType>
      <xs:sequence minOccurs ="2" maxOccurs ="4">
        <xs:element name ="Book">
          <xs:complexType>
            <xs:sequence>
              <xs:element name ="Book_id" type ="xs:integer"/>
              <xs:element name ="Author">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base ="xs:string">
                      <xs:attribute name ="gender" use ="optional" type ="xs:string"/>
                      <xs:attribute name ="id" use ="optional" type ="xs:integer"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
              <xs:element name ="Title" type ="xs:string"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== shumailakhan4810/XML-JASON/XML/02.Schema/book.xml
<?xml version="1.0" encoding="utf-8"?>
<books xmlns:xsi ="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation ="book.xsd" >
  <Book>
    <Book_id>12</Book_id>
    <Author>Sedra Smith</Author>
    <Title>XML By Example</Title>
  </Book>
  <Book>
    <Book_id>12</Book_id>
    <Author gender ="Male" id="1001">Sedra Smith</Author>
    <Title>XML By Example</Title>
  </Book>
  <Book>
    <Book_id>12</Book_id>
    <Author>Sedra Smith</Author>
    <Title>XML By Example</Title>
  </Book>
  <Book>
    <Book_id>233</Book_id>
    <Author>Sedra Smith</Author>
    <Title>eafea</Title>
  </Book>
</books>
